version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEVELOPMENT=DEVELOPMENT
      - PORT=4000
      - MONGO_URI=mongodb://db/task-database
      - JWT_SECRET=aadaljdfjadf34jl52__..%&$$ajfakljfklaja.
    ports:
      - $PORT:$PORT
    links:
      - db
    volumes:
      - .:/app
    command: npm run dev
  db:
    image: mongo
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: